CREATE TABLE [TRTVEICULO](
	[IDVEICULO] [int] NOT NULL,
	[DESCRICAO] [varchar](254) NOT NULL,
	[MARCA] [varchar](100) NOT NULL,
	[MODELO] [varchar](100) NOT NULL,
	[ANOFAB] [int] NOT NULL,
	[ANOMOD] [int] NOT NULL,
	[IDLOCALIDADE] [int] NOT NULL,
	[CODESTADO] [varchar](2) NOT NULL,
	[PRECO] [dbo].[DVALOR4] NOT NULL,
	[VENDEDOR] [varchar](250) NOT NULL,
	[DATAATUALIZACAO] [datetime2](7) NOT NULL,
	[STATUS] [bit] NOT NULL,
	[RECCREATEDBY] [varchar](50) NULL,
	[RECCREATEDON] [datetime2](7) NULL,
	[RECMODIFIEDBY] [varchar](50) NULL,
	[RECMODIFIEDON] [datetime2](7) NULL,
 CONSTRAINT [PKTRTVEICULO] PRIMARY KEY CLUSTERED 
(
	[IDVEICULO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TRTVEICULO]  WITH CHECK ADD  CONSTRAINT [FKTRTVEICULO_GETD] FOREIGN KEY([CODESTADO])
REFERENCES [dbo].[GETD] ([CODETD])
GO

ALTER TABLE [dbo].[TRTVEICULO] CHECK CONSTRAINT [FKTRTVEICULO_GETD]
GO

ALTER TABLE [dbo].[TRTVEICULO]  WITH CHECK ADD  CONSTRAINT [FKTRTVEICULO_GLOCALIDADE] FOREIGN KEY([IDLOCALIDADE])
REFERENCES [dbo].[GLOCALIDADE] ([CODLOCALIDADE])
GO

ALTER TABLE [dbo].[TRTVEICULO] CHECK CONSTRAINT [FKTRTVEICULO_GLOCALIDADE]
GO


